### ISSUE TITLE
No input mapper for "VideoCall" inputs

### ISSUE THREAD

**Issue by jmarshalltech** [jensstigaard/vmix-js-utils#19]
`Error: Not implemented yet. There was not found an Input Mapper for type... VideoCall`

https://github.com/jensstigaard/vmix-js-utils/blob/74c4485611548db37a3ec486708801c4ad275f56/src/xml-api/inputs.ts#L117

Here's an example of a videoCall input and its attributes for reference

`<input key="b7c390be-ad89-421c-82bb-c0fba1445734" number="1" type="VideoCall" title="Call 1234567890" shortTitle="Call 1234567890" state="Running" position="0" duration="0" loop="False" muted="True" volume="100" balance="0" solo="False" audiobusses="M" meterF1="0" meterF2="0" gainDb="0" callPassword="1234567890" callConnected="False" callVideoSource="Output2" callAudioSource="BusA">Call 1234567890</input>`

I would do this myself but it's a bit beyond my capability.

**Comment by jensstigaard** [comment]
I just released a fix for this, implementing the input mapper for video call.

**Comment by jmarshalltech** [comment]
Thank you!
